//! Byte-for-byte parity tests against the Python GDS reference implementation.
//!
//! These vectors were generated by running the Python GDS CCSDS modules
//! (`spacepackets.ccsds.spacepacket` + the project's
//! `space_data_link.SpaceDataLinkFramerDeframer`) on known inputs.  See
//! `tests/python_parity_vectors.txt` for the script that produced them.

use fprime_ccsds::{
    space_packet::SpacePacketFramer, ChainedFramer, SpacePacketDeframer, TcFramer, TmDeframer,
};
use fprime_frame::{Deframer, Framer};

fn hex_decode(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

#[test]
fn space_packet_matches_python_bytes() {
    // payload = leading APID U32 = 0x42, then "hello".
    let payload = hex_decode("0000004268656c6c6f");
    let mut framer = SpacePacketFramer::new();
    let bytes = framer.frame(&payload).unwrap();
    let expected = hex_decode("1042c00000080000004268656c6c6f");
    assert_eq!(
        hex::encode(&bytes),
        hex::encode(&expected),
        "Space Packet wire format must match the Python `SpacePacketFramerDeframer.frame` output"
    );
}

#[test]
fn tc_raw_matches_python_bytes() {
    // No inner protocol; raw 5-byte payload framed as a TC transfer frame.
    let payload = hex_decode("0102030405");
    let mut framer = TcFramer::new(0x44, 1).unwrap();
    let bytes = framer.frame(&payload).unwrap();
    let expected = hex_decode("2044040b000102030405dd48");
    assert_eq!(hex::encode(&bytes), hex::encode(&expected));
}

#[test]
fn chain_sp_then_tc_matches_python_bytes() {
    // Same as the Python `space-packet-space-data-link` chain.
    let payload = hex_decode("0000004268656c6c6f");
    let inner: Box<dyn Framer> = Box::new(SpacePacketFramer::new());
    let outer: Box<dyn Framer> = Box::new(TcFramer::new(0x44, 1).unwrap());
    let mut chain = ChainedFramer::new(inner, outer);
    let bytes = chain.frame(&payload).unwrap();
    let expected = hex_decode("20440415001042c00000080000004268656c6c6f0047");
    assert_eq!(hex::encode(&bytes), hex::encode(&expected));
}

#[test]
fn space_packet_round_trip_through_python_built_bytes() {
    // Ground (uplink) generates the exact bytes the FSW would produce on TM
    // downlink, so we deframe them and confirm the body comes back out.
    // (We re-use the SP wire bytes but flip the type bit to TM for the test.)
    // The simpler version: build a TM-typed packet manually and confirm
    // the deframer extracts the body verbatim.
    use fprime_ccsds::space_packet::{PacketType, SpacePacketHeader, SEQ_FLAGS_UNSEGMENTED};
    let body = b"\x00\x00\x00\x05hi";
    let h = SpacePacketHeader {
        version: 0,
        packet_type: PacketType::Tm,
        sec_hdr_flag: false,
        apid: 5,
        seq_flags: SEQ_FLAGS_UNSEGMENTED as u8,
        seq_count: 0,
        data_len_minus_one: (body.len() as u16) - 1,
    };
    let mut wire = h.pack().to_vec();
    wire.extend_from_slice(body);
    let mut d = SpacePacketDeframer::new();
    d.push(&wire);
    let out = d.pop().expect("frame");
    assert_eq!(out.as_slice(), body);
}

#[test]
fn tm_deframer_drops_garbage_then_finds_frame() {
    use fprime_ccsds::space_data_link::build_tm_frame;
    let mut wire = vec![0xFF; 8];
    wire.extend_from_slice(&build_tm_frame(0x44, 1, b"\x00\x00\x00\x05hi", 32));
    let mut d = TmDeframer::new(0x44, 1, 32).unwrap();
    d.push(&wire);
    let out = d.pop().expect("frame");
    assert!(out.starts_with(b"\x00\x00\x00\x05hi"));
}
